#!/usr/bin/env bash

if [ $# = 0 ]; then
	printf "Usage: `basename $0` [st|f|r]\n"
	exit
fi

ACTION=$1

for dir in */; do
  cd $dir
  echo "--------------------------------------> Git Repo: $dir"
  echo ""
  git $ACTION
  cd ..
done

echo "--------------------------------------> All git dirs updated!"
